CREATE TABLE folds
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path VARCHAR(100)NULL DEFAULT NULL,
    fold VARCHAR(100)NULL DEFAULT NULL,
    file VARCHAR(100)NULL DEFAULT NULL
);

CREATE TABLE songs
(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    path VARCHAR(100)NULL DEFAULT NULL,
    fold VARCHAR(100)NULL DEFAULT NULL,
    file VARCHAR(100)NULL DEFAULT NULL,

    name VARCHAR(100)NULL DEFAULT NULL,
    artist VARCHAR(100)NULL DEFAULT NULL,

    cover VARCHAR(100)NULL DEFAULT NULL,
    lrc VARCHAR(100)NULL DEFAULT NULL,
    url VARCHAR(100)NULL DEFAULT NULL
);

